backend:
  name: github
  repo: mathssyfy/mathssyfy-site
  branch: master # Branch to update (optional; defaults to master)
media_folder: "src/blog/images"
public_folder: "./images/"
media_library:
  name: cloudinary
  config:
    cloud_name: dpw19qolx
    api_key: 431889228911483
collections:
  - name: "sidebar"
    label: "Sidebar"
    folder: "src/.vuepress/sidebar"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields: 
      - label: "Title"
        name: "title"
        widget: "string" 
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Author", name: "author", widget: "string", default: 'David Couronné'}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Post", name: "post", widget: "boolean", default: true}
      - {label: "Tags", name: "tags", widget: "list", default: ["news"]}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        required: false
        tagname: ''
        media_library:
          config:
            default_transformations:
              -   - fetch_format: auto
                    width: 300    
                    quality: auto
                    crop: fill
                    effect: grayscale